### ISSUE TITLE
Chapters Overwritten with Duplicates

### ISSUE THREAD

**Issue by SpeedyDoggo** [olivierkes/manuskript#1320]
I was trying to use the side by side editing feature (where you can supposedly view two different sections at once.) It was being finicky but I managed to get it working. While in this mode, I moved a few texts around the tree.

The text I moved overwrote one of the texts they displaced when I moved them. I now had two versions of the moved file and none of the old file. I didn't move either of these texts more than one file, so they essentially just overwrote the file they swapped positions with.

I'm on Windows 10, using the ManuskriptW.exe of 0.16.1-5a10925. I've attached the log file of that session to this post. 'Introduction'/'Chapter 5' overwrote 'Tutelage', and 'Presque Vu' overwrote something that I'd just renamed. Might make it easier to spot what happened.

[2024-08-18_09-48-20_manuskript#12060.log](https://github.com/user-attachments/files/16650467/2024-08-18_09-48-20_manuskript.12060.log)

**Comment by policieuxjp** [comment]
Experienced exactly the same behaviour (moved a chapter, ended with a duplicate one that overwrote another one).
I'm on Linux Ubuntu 22.04, Manuskript 0.16.1.
[2024-12-19_14-22-16_manuskript#123704.log](https://github.com/user-attachments/files/18198902/2024-12-19_14-22-16_manuskript.123704.log)
Chapter was "Introduction d'Aurore réunion"
Loved using the software so far, but I'm now super scared to lose a chapter ...

**Comment by SpeedyDoggo** [comment]
I ended up starting to use Github Desktop to keep things up to date between my devices, which has the side effect of letting me go back and save whatever chapter got wiped when this happens. Maybe that could be of use to you, @policieuxjp ? At least until this issue is worked out.

**Comment by policieuxjp** [comment]
Thanks for the tip, I'm using git and a script to track changes now.

**Comment by Mat1999** [comment]
I ran into this problem too on 16.1, fortunately I was already using Github to backup my writings. For me it always occured after creating and renaming a new chapter and then trying to move it, altough I'm not sure that's the cause of the problem.
The chapter "2-A_gy-ztesek_-rj-k_a_t-rt-nelmet.md" was the one that was overwritten after moving the other one ("3-Enrica.md") around.
I just saw that 17.0 was released, so I don't know if this problem still exists on that version. I didn't see it being fixed in the changelog, but who knows.

[2025-07-14_17-55-20_manuskript#21444.log](https://github.com/user-attachments/files/21220453/2025-07-14_17-55-20_manuskript.21444.log)

**Comment by Furyous20** [comment]
I can confirm that this is still a problem. I am on the newest version (17.0) and moving a New chapter over an existing one completely deleted the old one, creating two New Files. The old writing is nowhere to be found and cannot be undone. I am on Linux Mint 22.1
